# Generated by Django 3.2.25 on 2025-09-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20250926_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='agenda',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
    ]
